### ISSUE TITLE
Create fedora_to_rof tool

### ISSUE THREAD

**Issue by msuhovec** [ndlib/rof#19]
First try at this: create tool 

rof/bin/fedora_to_rof  --pid <fedora_pid>  --fedora <URL>  --user <fedora_user:password> --bendo <URL>  --output-file <file_path>

Given a fedora object with Pid <pid> that was ingested by Bendo,  produce an ROF file <filepath>,
which may be ingested by RoF ingest to update metadata changed by the Curate GUI.

**Comment by dbrower** [comment]
Probably don't need the `--bendo` option.

Do include an option `--download-content` to download datastream with content >= 1024 bytes into auxiliary files. (if option is missing then general datastreams with content >= 1024 bytes is ignored.

Actually the logic would be: If (datastream size is < 1024 bytes) AND (the datastream is valid utf-8), put the datastream content in the JSON file. Otherwise, don't.

**Comment by msuhovec** [comment]
I am ready to close this- code inspection results are in, and tests.
