### ISSUE TITLE
Normalize CSV split characters on "|"

### ISSUE THREAD

**Issue by jeremyf** [ndlib/rof#22]
At present, both pipe `|` and semi-colin `;` are used to differentiate multi values in CSV. Normalize the split process to use `|`.

Suggestion is that a constant be defined (and frozen) saying that it is the split character (suggestions `Rof::CSV_MULTI_VALUE_DELIMITER`).

**Comment by dbrower** [comment]
Every field but the access control field splits on pipe, `|`. https://github.com/ndlib/rof/blob/master/lib/rof/translate_csv.rb#L71

Only the access control field splits on semicolon, `;`. https://github.com/ndlib/rof/blob/master/lib/rof/access.rb

I wonder if there are any existing systems that need to be adjusted for this change...it seems to be minimal since it is only used at the CSV -> ROF conversation step.

My suggestion for the constant name is `Rof::PIPE_CHARACTER`.
